name: FWParties
version: @version@
main: it.forgottenworld.fwparties.FWParties
api-version: 1.16
authors: [ tigierrei ]
commands:
  party:
    description: Party command
    aliases:
      - p
      - fwparty
      - fwparties
    permission: party.default
    default: true
  pc:
    description: Party chat command
    aliases:
      - partychat
      - fwpartychat
      - fwpartieschat
    permission: party.chat
    default: true
  pos:
    description: Party position command
    aliases:
      - position
      - fwpartypos
      - fwpartiespos
      - fwp
      - fwpos
    permission: party.pos
    default: true
  partyadmin:
    aliases:
      - pa
      - partya
    description: Party admin commands
    permission: party.admin
    default: op