name: Parties
version: 1.1.1
main: it.filippocavallari.Parties
description: "Lightweight party plugin"
api-version: 1.17
authors: [ tigierrei ]
depend:
  - KotlinLib
commands:
  party:
    description: Party command
    permission: parties.party.*
    default: true
  pc:
    description: Party chat command
    aliases:
      - partychat
    permission: parties.chat
    default: true
  pos:
    description: Party position command
    aliases:
      - position
    permission: party.pos
    default: true
  partyadmin:
    aliases:
    description: Party admin commands
    permission: party.admin
    default: op