name: FWParties
version: @version@
main: it.forgottenworld.fwparties.FWParties
api-version: 1.16
authors: [ tigierrei ]
commands:
  party:
    description: Party command
    aliases:
      - p
      - fwparty
      - fwparties
    permission: party.*
    default: true
  pc:
    description: Party chat command
    aliases:
      - partychat
      - fwpartychat
      - fwpartieschat
    permission: party.*
    default: true
  pos:
    description: Party position command
    aliases:
      - position
      - fwpartypos
      - fwpartiespos
      - fwp
      - fwpos
    permission: party.*
    default: true